[package]
name = "export"
version = "0.1.0"
authors = ["william <zrf802@alumni.ku.dk>"]
edition = "2018"

[lib]
name = "read_cube"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = ">=0.7.0"
features = ["extension-module"]

[dependencies]
ndarray = "0.12.1"
